DROP DATABASE IF EXISTS notetaker_db;

CREATE DATABASE notetaker_db;

USE notetaker_db;

CREATE TABLE notes(
note_id INTEGER(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
note_title VARCHAR(50) NOT NULL ,
note_text VARCHAR(255),
created_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
created_by VARCHAR(50) DEFAULT 'Guest'
);

SELECT * FROM notes;